params:
  epochs: 5
  batch_size: 32
  no_of_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_data_size: 5000

artifacts:
  artifacts_dir: artifacts
  model_dir: models
  plot_dir: plots
  checkpoint_dir: checkpoints
  model_name: model.h5
  plot_name: model_plot.jpg

logs: 
  log_dir: logs
  general_logs: general logs
  tensorboard_logs: tensorboard logs